# Generated by Django 5.1.5 on 2025-02-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created_at',
        ),
    ]
