# Generated by Django 5.1.5 on 2025-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puntos',
            field=models.FloatField(default=0),
        ),
    ]
