# Generated by Django 5.1.5 on 2025-02-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultima_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
