# Generated by Django 5.1.5 on 2025-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_fecha_ultima_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultimo_canje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
