# Generated by Django 5.1.5 on 2025-02-02 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_transaccion', models.CharField(choices=[('compra', 'Compra'), ('canje', 'Canje')], default='compra', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='puntos.compra')),
                ('recompensa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='puntos.recompensa')),
            ],
        ),
    ]
