# Generated by Django 5.1.5 on 2025-02-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0002_recompensa_transaccionpunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionpunto',
            name='cantidad_puntos',
            field=models.FloatField(default=0),
        ),
    ]
