# Generated by Django 5.1.5 on 2025-02-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0003_transaccionpunto_cantidad_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='nombre',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='puntos_requeridos',
            field=models.FloatField(default=0),
        ),
    ]
