# Generated by Django 5.1.5 on 2025-02-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0004_recompensa_activa_recompensa_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionpunto',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puntos.compra'),
        ),
        migrations.AlterField(
            model_name='transaccionpunto',
            name='recompensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puntos.recompensa'),
        ),
    ]
